version: '2'
services:
  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=YOUR-API-KEY
      - ZONE=example.com # root domain i.e. example.com
      - SUBDOMAIN=subdomain # ddns subdomain without the root
      - PROXIED=false
